caraml-dev/helm-charts

- .github/workflows/lint-test.yaml
Add condition to install metallib in workflow, else PRs that do not make changes to any charts will fail.
> chore(cicd): Add condition for install metallib

- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
Upgrade chart version for gen-dep-installer for Knative-serving-istio
* Upgrade chart version for gen-dep-installer for Knative-serving-istio
> chore: Upgrade chart version for gen-dep-installer for Knative-serving-istio

- charts/routes/Chart.yaml
- charts/routes/README.md
Update routes chart to used released deps
> chore(routes): Update routes chart to used released deps

- charts/helm-dep-installer/Chart.yaml
- charts/helm-dep-installer/README.md
- charts/helm-dep-installer/files/run.sh
Remove extra space in the uninstall script
> fix(gdi): Remove extra space in the uninstall script

- charts/knative-serving-istio/Chart.lock
- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
upgrade gdi chart version to 0.2.1
upgrade gdi chart version to 0.2.1
> chore(knative-serving): upgrade gdi chart version to 0.2.1

- charts/kserve/Chart.yaml
- charts/kserve/README.md
- charts/kserve/values.yaml
upgrade knative-serving-istio chart version 1.0.6
upgrade knative-serving-istio chart version 1.0.6
> chore(kserve): upgrade knative-serving-istio chart version 1.0.6

- charts/kserve/Chart.yaml
- charts/kserve/README.md
* bump use gdi to version 0.2.1
> fix(kserve): Bump kserve to 0.8.8

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
Add missing mlp key in values
Add missing mlp key in values
> fix(merlin): Add missing mlp key in values

- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/templates/merlin-service.yaml
- charts/merlin/templates/mlflow-service.yaml
- charts/merlin/values-global.yaml
- charts/merlin/values.yaml
Same as #31 but for merlin charts
> feat(merlin): Configure merlin to use global values if available

- charts/common/Chart.yaml
- charts/common/templates/_helper.tpl
- charts/common/templates/_routes.tpl
This PR adds conditional checks in common chart's named template.
* `oauthclient` renamed to `oAuthClient`
> fix(common): Patch common chart

- charts/common/Chart.yaml
This PR bumps the chart version of common to 0.2.2. Previous change bumped appVersion instead of chart version.
> chore(common): Bump common chart version to 0.2.2

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- charts/knative-serving-istio/Chart.lock
- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
- charts/knative-serving-istio/ci/ci-values.yaml
- charts/knative-serving-istio/values.yaml
Configure reasonable defaults for infrastructure components
Adding resource constraints for knative-serving-istio chart.
> chore(knative-serving-istio): Default values resources knative serve istio

- charts/kserve/Chart.lock
- charts/kserve/Chart.yaml
- charts/kserve/README.md
- charts/kserve/ci/test-values.yaml
- charts/kserve/values.yaml
Configure reasonable defaults for infrastructure components
Adding resource constraints for kserve chart.
> chore(kserve): Add default values for resources in kserve chart

- charts/mlp/Chart.lock
- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/values.yaml
This PR adds global field to values.yaml
* bump common chart to 0.2.2
> fix(mlp): Bump mlp to use common 0.2.2, add global to values

- charts/common/Chart.yaml
- charts/common/templates/_helper.tpl
See https://github.com/caraml-dev/helm-charts/pull/52#discussion_r1011148636
> chore(common): Follow existing mlp & merlin conf

- charts/common/Chart.yaml
- charts/common/templates/_helper.tpl
> fix(common): Fix typo

- charts/routes/Chart.lock
- charts/routes/Chart.yaml
- charts/routes/README.md
- charts/routes/values.yaml
Update routes chart to use common chart 0.2.4
* Bump routes version to 0.1.3
* Change `global.oauthclient` to `global.oauthClientID`
> chore(routes): Patch routes chart

- charts/mlp/Chart.lock
- charts/mlp/Chart.yaml
- charts/mlp/README.md
> chore(mlp): Patch mlp to use common 0.2.4

- .github/workflows/chart-bumper.yaml
- scripts/chart_bumper.py
Incorrect config path in chart-testing (list-changed) step for chart bumper
* Fix ct.yaml path in chart bumper workflow
* Update github action versions to latest in chart bumper workflow
> fix: Chart bumper workflow had incorrect ct.yaml config

- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
common chart upgrade to fix the helper function.
* update common chart version
> chore(merlin): Update chart version for common chart and merlin

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
Get fixes in the umbrella chart
Dependencies versions.
> chore: bump mlp chart version in caraml and merlin charts

- charts/common/Chart.yaml
- charts/common/README.md
- charts/common/templates/_names.tpl
Move redundant name generations logic to common as much as possible
> feat: Add helper functions to generate names for common resources

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
- charts/caraml/values.yaml
Upgrade authz dep version with necessary value changes.
* Upgrade authz dep version, add dbSecretKey in global values
* Upgrade commons chart version
> chore(caraml): Update authz chart version

- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/tests/merlin_deployment_test.yaml
Use common functions and remove redundant name generator templates for postgres.
* Update database values in the Merlin deployment
* Add unit tests.
> chore(merlin): Update postgres related names with common template functions

- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
up mlp chart version in merlin chart
> chore(merlin): upgrade mlp chart version

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
Update repo url for authz in caraml chart.
* Update repo url for authz in caraml chart.
> chore(caraml): Update authz chart repo url; upgrade chart version

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
Bumping the routes chart version in the umbrella chart
- routes chart dependency version
> chore: bump routes chart version

- charts/routes/Chart.yaml
- charts/routes/README.md
The previous version was not released, so bumping the patch version again.
- patch version bumped
> chore(route): bump version to retrigger repo deployment

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/values.yaml
Co-authored-by: yadavsunny05 <yadav.sunny05@gmail.com>
* Gopay org needs more flexibility on setting labels of Merlin resources
* Update Merlin version to 0.26 which has capability to set label prefix. Need this PR https://github.com/gojek/merlin/pull/346 to be merged first.
> feat(merlin): Update Merlin to 0.26 that include deploymentLabelPrefix config.

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/deployment.yaml
- charts/mlp/values.yaml
This PR adds tolerations for mlp chart.
> feat: add tolerations for mlp chart

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/deployment.yaml
- charts/mlp/values.yaml
Add the missing service account created for the mlp deployment
* modify deployment
> fix(mlp): Add service account to mlp deployment

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/tests/merlin_deployment_test.yaml
- charts/merlin/values.yaml
Resource configuration was implemented in a previous PR to Merlin repository (https://github.com/gojek/merlin/pull/351) and this PR handles the required helm chart changes to utilise the configuration change.
Add `imageBuilder.resources` field to values file.
> feat: Incorporate imagebuilder resource changes to Merlin helm chart

- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/deployment.yaml
- charts/xp-management/values.yaml
* Add extraLabels to values and to deployment template.
> feat: Add support for deployment labels

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/values.yaml
https://github.com/caraml-dev/merlin/pull/380
> chore(merlin): Add IMG_BUILDER_JOB_SAFE_TO_EVICT to Merlin deployment

- charts/caraml-store/Chart.yaml
- charts/caraml-store/README.md
- charts/caraml-store/templates/registry/hpa.yaml
- charts/caraml-store/templates/serving/hpa.yaml
- charts/caraml-store/values.yaml
Add support for horizontal pod scaling for both registry and serving services.
> feat(caraml-store): Support horizontal pod autoscaling for caraml store services

- charts/xp-treatment/Chart.lock
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
Bump version to use latest version of xp-management (0.1.13)
> chore(xp-treatment): Bump xp-management version to 0.1.13

- .github/workflows/chart-bumper.yaml
- scripts/chart_bumper.py
ref: https://github.com/caraml-dev/helm-charts/pull/262
fixing workflow
> ci: fix chart bumper workflow

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
> chore(caraml): manual update for turing version

- charts/xp-treatment/Chart.lock
> chore: manual upgrade for xp-treatment chart dep version; Update lock file

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
> chore: manual upgrade for caraml chart dep version

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/values.yaml
Add env vars to support configuration of changes introduced in https://github.com/caraml-dev/merlin/pull/409
Adding new env vars to Merlin's deployment template.
> feat(merlin): Add authz caching config

- charts/xp-treatment/Chart.lock
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
Update `xp-treatment`'s dependency on the management service to the latest version.
> chore(xp-treatment): Bump up dependency on xp-management

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/values.yaml
In #254, a new schema was introduced due to the refactored Helm chart. However, there were some tiny errors with the formatting of the values file. In addition https://github.com/caraml-dev/merlin/pull/389 which has been merged to the main branch of Merlin requires a new config field to be introduced in its Helm chart values file for the API server to start up correctly. This PR fixes those issues. 
Note: This PR will be merged to get a new Helm chart published for Merlin, which will then be used to update the Merlin CICD workflow, before I'll come back to this repo to update the default Merlin image used.
- `charts/merlin/values.yaml` - Correction of an incorrect field name and misalignment of a config block
- `charts/merlin/templates/_helpers.tpl` - Addition of the `ArtifactServiceType` …
> fix(merlin): Fix incorrect formatting of chart values

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
- scripts/generate-cluster-creds.sh
Merlin's chart version number has been given a minor version bump. This PR serves to update the overarching CaraML chart manually with the new Merlin minor version.
- `charts/caraml/Chart.yaml` 
- `charts/caraml/Chart.lock`
- `charts/caraml/README.md`
> chore(caraml): Update merlin chart version manually

- charts/caraml/Chart.yaml
- charts/caraml/README.md
> chore(caraml): Bump caraml minor version to 0.6.15

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
> chore(caraml): Bump caraml to 0.6.17 with merlin to 0.11.7

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/keto-bootstrap-job.yaml
Add support for node selector and tolerance for bootstrap job so that the pod can be scheduled in tainted node pool.
- Add node selector and tolerance to bootstrap job.
> feat: support node selector and tolerance for bootstrap job

- charts/routes/Chart.yaml
- charts/routes/README.md
- charts/routes/templates/gateway.yaml
- charts/routes/values.yaml
Enable https redirect in gateway resource in routes chart
- [ x] Chart version bumped
- [ x] README.md updated
> feat: Add option to perform https redirect in gateway

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
In next upcoming release of merlin, merlin will support publishing prediction log from pyfunc, this PR aims to add the necessary configuration for that new capability
> feat(merlin): Add pyfunc publisher config

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
Fix typo in https://github.com/caraml-dev/helm-charts/pull/385
PredictionJobBaseImages should be PredictionJobBaseImage
> chore(merlin): Fix typo, PredictionJobBaseImages should be PredictionJobBaseImage
