caraml-dev/helm-charts

- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
* Helm chart currently not installable when repository is not cloned, this PR fixes this issue.
* Point dependencies to repo url instead file uri
> chore(knative): Update deps in knative-serving-istio charts

- charts/kserve/Chart.yaml
- charts/kserve/README.md
This PR modifies kserve deps to reference the released version of cert-manager-base Helm chart instead of the file path to the helm chart.
> chore(kserve): Modify kserve to use release cert-manager-base

- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
- charts/knative-serving-istio/values.yaml
- charts/kserve/Chart.yaml
- charts/kserve/README.md
- charts/kserve/values.yaml
This PR enables the istioIngressGateway dependency that was previously disabled due to wrong field set in values.yaml
> fix(knative-serving-istio): Fix istioIngressGateway dep for knative-serving-istio

- .github/workflows/release.yaml
Release workflow is currently broken because of missing dependency.
> fix(caraml-store): Add bitnami repository to release workflow

- .github/workflows/lint-pr.yaml
Get rid of the warning:
```
[Validate PR title]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: amannn/action-semantic-pull-request
```
Updated linter version
> ci(lint): update version of PR title linter

- .github/CODEOWNERS
The feast dev team must be involved into the caraml-store chart reviews
> ci: update owners for caraml-store chart

- charts/caraml-store/Chart.yaml
- charts/caraml-store/README.md
- charts/caraml-store/templates/registry/configmap.yaml
- charts/caraml-store/templates/registry/secret.yaml
- charts/caraml-store/templates/registry/servicemonitor.yaml
- charts/caraml-store/templates/serving/deployment.yaml
- charts/caraml-store/templates/serving/secret.yaml
- charts/caraml-store/templates/serving/servicemonitor.yaml
The deployment commands and secret for the serving component is currently wrongly configured to use the values for registry rather than serving.
- [ x] Chart version bumped
- [ x] README.md updated
> fix(caraml-store): Fix template mistakes

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- charts/helm-dep-installer/Chart.yaml
- charts/helm-dep-installer/README.md
- charts/helm-dep-installer/files/run.sh
Uninstaller via generic-dep-installer chart was using kubectl command instead of the helm command. Hence the sub-dependencies are not being uninstalled. 
* Use `helm uninstall` in GDI uninstall step.
* Dynamically add helm repo in GitHub pipelines.
> fix(gdi): Uninstall step in generic-dep-installer to use helm command.

- .github/workflows/release.yaml
Release pipeline is broken because of a missing flag
* add missing flag in the `Add dependency charts` step.
> ci: fix release pipeline, add missing arg in workflow step

- charts/kserve/Chart.yaml
- charts/kserve/README.md
- charts/kserve/values.yaml
Update the chart version to include the latest gen-dep-installer  chart release.
Update the chart version to include the latest gen-dep-installer  chart release.
> chore(kserve): upgrade gen-dep-installer, knative-serving-istio chart version

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
Release workflow failing because of the `file://` protocol in repo URLs.
> ci: fix release pipeline, exclude file based repo URLs in Add dependancy step

- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
Update chart version for gen-dep-installer and kserve to get latest generic-dep-installer changes.
Update chart version for gen-dep-installer and kserve to get latest generic-dep-installer changes.
> chore(merlin): Update chart version for gen-dep-installer and kserve

- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
New chart version in GDI chart fixing uninstall-related bugs.
upgrade GDI chart version to 0.2.0
> chore(knative-serving): upgrade gdi chart version to 0.2.0

- charts/kserve/Chart.yaml
- charts/kserve/README.md
- charts/kserve/values.yaml
New chart version in GDI chart fixing uninstall-related bugs.
upgrade GDI chart version to 0.2.0
> chore(kserve): upgrade gdi chart version to 0.2.0

- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/values.yaml
Should be merged after #43 is merged
> fix(merlin): Bump merlin to use gdi 0.2.1, kserve 0.8.8

- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/values-global.yaml
- charts/routes/Chart.yaml
It adds a namedtemplate to fix the `"http://%s!(nil).nip.io` error when rendering feast api host. Returns "" when global.feast is empty.
* upgrade common chart to 0.2.4
* upgrade mlp chart to 0.3.1
* `global.oauthclient` change to `global.oauthClientID`
> fix(merlin): Update merlin chart to use new common chart

- .github/dependabot.yml
Updating Github actions on a regular basis to get the latest versions manually is a repetitive task that can be automated by GitHub-provided dependabot. 
Add dependabot config to GitHub config.
> ci: Add dependabot config to auto create PRs for GitHub actions version upgrade

- .github/workflows/chart-bumper.yaml
- scripts/chart_bumper.py
Every time there is a new version of the helm chart released, the updated version needs to be propagated up to all the charts where it is a dependency. This creates a lot of manual effort to create PRs. This new workflow aims to automatically create a PR for updating the version of the released chart in whichever charts are applicable. This caters to both dependencies listed in the Chart.yaml file and the ones added via generic-dep-installer.
The idea for creating this came from this [blog](https://blog.promaton.com/how-to-set-up-automated-helm-chart-upgrades-e292192a9aad). It uses the tool: [update-cli](https://www.updatecli.io/).
* Add new ci workflow.
The script goes through all charts and checks if there is a newer version of the listed dependencies. For each new version of a …
> ci: Add workflow to create Chart bump PR on every release

- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
- charts/knative-serving-istio/templates/_helpers.tpl
- charts/knative-serving-istio/templates/peer-authentication/webhook.yaml
- charts/knative-serving-istio/templates/validating-webhooks/webhook-config.yaml
- charts/knative-serving-istio/values.yaml
Similar to https://github.com/caraml-dev/helm-charts/pull/68 . Knative 1.0.1 has issue on handling liveness probe when using gRPC protocol and is fixed in version [1.2.3 or later](https://github.com/knative/serving/releases/tag/knative-v1.2.3).
The modifications are made base of the diff between knative istio 1.0.0 manifest and knative  istio 1.3.0 manifest. It mainly modifies labels and docker images versions.
Note that knative net istio component doesn't create new release for every new patch of knative serving core hence the patch version is always 0.
> feat: Update knative-serving istio to 1.3.0

- charts/knative-serving-istio/Chart.lock
- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
- charts/knative-serving-istio/ci/ci-values.yaml
- charts/knative-serving-istio/files/run_test.sh
- charts/knative-serving-istio/templates/test-resources/job.yaml
- charts/knative-serving-istio/values.yaml
Test workflow ends up in a failed state when multiple charts are being updated at the same time which has istio as a common dependency.  For eg. If a PR has changes in caraml-routes and knative-serving-istio. Tests fail to install for routes because istio-system namespace is already created by knative-serving-istio chart. Since chart tester uses the same kind cluster to test.
To avoid this, Adding a different istio namespace for knative-serving-istio chart. This also needs the tests in the chart to use the namespace from the values file instead of hardcoding it to the test script.
Releasing this chart earlier to https://github.com/caraml-dev/helm-charts/pull/70 so that this released version can be used in the kserve chart, so that it passes the helm tests as well. 
* Update helm tests to …
> fix(knative-serving-istio): Use istio namespace from values file during helm tests

- charts/knative-serving-core/README.md
- charts/knative-serving-istio/Chart.lock
- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
Update the depedency version of knative-serving-istio, knative-serving-core  from 1.1.2 to 1.3.2
Version bump to 1.3.10 for serving-istio. Added to the readme, hopefully it can help to be clearer which knative release it originated from as we bump the minor versions.
Updated readme and test chart test dep version
> test: Knative update test dep

- charts/caraml-store/Chart.yaml
- charts/caraml-store/README.md
- charts/caraml-store/templates/serving/servicemonitor.yaml
The match label for caraml serving's service monitor is currently wrongly set to regisry's.
Update the match label to use the correct values.
> fix(caraml-store): fix match label for serving component's service monitor

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/ingress.yaml
- charts/mlp/values.yaml
Path type is mandatory while creating an ingress in kube. Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types. Ingress created in mlp did not have it in the template. This PR will add the key for the same. 
* Add pathType to ingress template.
> fix(mlp): Ingress error due to missing pathType key

- charts/caraml-store/Chart.yaml
- charts/caraml-store/README.md
- charts/caraml-store/templates/registry/servicemonitor.yaml
- charts/caraml-store/templates/serving/servicemonitor.yaml
Due to a typo the endpoint is not being set correctly for the servicemonitor.
Updated the endpoint to the correct value.
> fix(caraml-store): fix endpoint for service monitor

- charts/knative-serving-core/Chart.yaml
- charts/knative-serving-core/README.md
- charts/knative-serving-core/templates/monitoring/monitoring.yaml
- charts/knative-serving-core/values.yaml
Monitoring values are misconfigured with the wrong selector key and port name.
- Use a standard selector key for pod monitors created for the knative-core chart. 
- The port name for metrics is updated to the latest.
> fix(knative-serving-core): Fix monitoring selector key and metrics port

- charts/common/Chart.yaml
- charts/common/templates/_routes.tpl
The helper function(`common.istio-lookup`) while trying to check the relevant key present in the context to do a lookup of istioIP, Was looking at an empty map always, hence getting the domain empty for the helper func (`common.get-external-hostname`
* Fix the if condition to check the right map for keys to be present.
> fix(common): Fix the istio lookup helper function

- charts/kserve/Chart.yaml
- charts/kserve/README.md
- charts/kserve/templates/serviceaccount.yaml
Redundant labels are causing validation errors in ArgoCD:
```
rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: 
rpc error: code = Unknown desc = error generating manifests: `sh -c helm template ${ARGOCD_APP_NAME} --version ${ARGOCD_ENV_HELM_CHART_VERSION} --repo ${ARGOCD_ENV_HELM_CHART_REPO} --namespace ${ARGOCD_APP_NAMESPACE} ${ARGOCD_ENV_HELM_CHART_NAME} -f ${ARGOCD_ENV_HELM_VALUES_FILE} > all.yaml && kubectl kustomize .`
failed exit status 1: error: map[string]interface {}(nil): yaml: unmarshal errors: line 11: mapping key "app.kubernetes.io/instance" already defined at line 6 line 13: mapping key "app.kubernetes.io/managed-by" already defined at line 7 line 10: mapping key "app.kubernetes.io/name" already …
```
> fix(kserve): fix redundant labels in kserve sa

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/_helpers.tpl
- charts/mlp/templates/configmap.yaml
- charts/mlp/templates/deployment.yaml
- charts/mlp/values.yaml
As of now, all the configuration values are passed to [`gojek/mlp`](https://github.com/gojek/mlp) via environment variables. With the growing complexity of the required config, this way of passing runtime config became inconvenient because it needed some sort of encoding to pass a complex struct/object data (i.e. serializing data as JSON-string. Example: [charts/mlp/values.yaml#L47](https://github.com/caraml-dev/helm-charts/blob/c06cb5d7bd046eb9533c796060a9446327101777/charts/mlp/values.yaml#L47)). 
This Draft PR [gojek/mlp!71 ](https://github.com/gojek/mlp/pull/71) brings support of reading MLP configuration from YAML config files, hence the changes introduced in this PR are adding support of the config file into MLP's chart.
* [`configmap`](https://github.com/caraml-dev/helm-charts/compa …
> refactor(mlp): Support configuration to be passed via ConfigMap

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/postgres-secret.yaml
- charts/mlp/values.yaml
A secret is created if external db is used. But ideally, it should be created if there is a need to create one. There can be cases where secrets are already created by external operators and we just need to point the right name and key in our templates. 
* Add check to create secret
> fix(mlp): Create a secret for db password only if enabled

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/templates/merlin-database-secret.yaml
- charts/merlin/templates/mlflow-database-secret.yaml
- charts/merlin/values.yaml
A secret is created if external db is used. But ideally, it should be created if there is a need to create one. There can be cases where secrets are already created by external operators and we just need to point the right name and key in our templates.
* Add check to create secret
* Add template to create secret for mlflow db if enabled
> fix(merlin): Create db secrets only when enabled

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/_helpers.tpl
- Trying to install 2 Helm release of MLP in the same namespace is failing without specifying name overrides due to same resource name being generated that lead to ownership conflict.
```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "mlp-0-3-4-encryption-key" in namespace "mlp" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "merlin-e2e-mlp-3797adfd": current value is "merlin-e2e-mlp-05f0fff9"
```
- Remove chart version from being used when generating `name` and `fullname`, the reason is that when we upgrade to new chart version, all resource name will also change. This will cause issue since a new …
> fix(mlp): Update name and fullname templating

- charts/common/Chart.yaml
- charts/common/README.md
https://github.com/caraml-dev/helm-charts/actions/runs/3571249668/jobs/6002955716 release failure due to existing chart version for common. upgrading.
> fix(common): Missed common chart upgrade

- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
Remove app version from resource name prefixes, It can cause recreation of resource for every chart version upgrade.
> chore(merlin): Use name overrides for resource names, Remove app version from resource names

- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
- charts/knative-serving-istio/templates/deployments/net-istio-controller.yaml
- charts/knative-serving-istio/templates/deployments/net-istio-webhook.yaml
- charts/knative-serving-istio/templates/monitoring/envoy-stats-metrics.yaml
- charts/knative-serving-istio/templates/monitoring/istiod-service-monitor.yaml
- charts/knative-serving-istio/templates/monitoring/knative-serving-pod-monitor.yaml
- charts/knative-serving-istio/values.yaml
Add Prometheus Monitors for Istiod service, ClusterGateway, IstioIngressgateway (via envoy-state-metrics), and the knative serving pods that are created for the predictors.  These monitors are supposed to be used in conjunction with the Prometheus stack for monitoring. These will be disabled by default When needed users can install Prometheus stack and enable these monitors to pull pod-exposed metrics. 
* Add istiod service monitor
* Add envoy-state-metrics pod monitor 
* Add queue-proxy pod monitor for knative serving pods.
> feat(knative-serving-istio): Add service and pod monitors for istiod, gateways and knative serving pods

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
- charts/routes/Chart.yaml
- charts/routes/README.md
Chart release incomplete due to [failed release](https://github.com/caraml-dev/helm-charts/actions/runs/3571249668/attempts/1) pipeline.  upgrading charts to release and change the repo URL in caraml chart to use released charts.
* upgrade chart version for caraml and routes
* change repo URL in deps for caraml chart.
> chore(caraml/routes): Upgrade version to release

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/configmap.yaml
- charts/mlp/values.yaml
To support https://github.com/gojek/mlp/pull/72
- `.Values.deployment.applications` section is added to Helm values
- Lower camel-case is used to define keys in the config map
> feat(mlp): add application configuration into MLP's runtime configuration

- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
- charts/knative-serving-istio/templates/monitoring/envoy-stats-metrics.yaml
- charts/knative-serving-istio/templates/monitoring/istiod-service-monitor.yaml
- charts/knative-serving-istio/templates/monitoring/knative-serving-pod-monitor.yaml
- charts/knative-serving-istio/values.yaml
- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/templates/service-monitor.yaml
- charts/merlin/values.yaml
Missing ServiceMonitor for merlin deployment.
Also, the current monitoring configuration in knative charts requires many toggles to control monitoring resources. 
- add ServiceMonitor
- adjust merlin labels template
- Use just one flag `monitoring.enabled`
> feat(merlin): add ServiceMonitor for merlin and refactor monitoring config in knative

- charts/caraml-authz/Chart.lock
- charts/caraml-authz/Chart.yaml
- charts/caraml-authz/README.md
- charts/caraml-authz/templates/_helpers.tpl
- charts/caraml-authz/values.yaml
Authz is failing to start/run init migrations when connecting to pg14.
```
level=error msg="Unable to ping SQL database backend" dsn="postgres://*:*@postgresql:5432/authz?sslmode=disable" error="pq: unknown authentication response: 10"  
```
looks like it's due to the Postgres version we have. Authz chart was made with default Postgres version as 8.0
> You have to upgrade the PostgreSQL driver or library on the client side so that it supports the scram-sha-256 authentication method introduced in PostgreSQL v10. ref: https://stackoverflow.com/a/64322735
* Upgrade the keto version to 0.5.4
* Upgrade the Postgres chart version in the authz chart to have Postgresql 14 db version.
> fix(authz): Upgrade keto app version to work with pg14

- charts/common/Chart.yaml
- charts/common/README.md
- charts/common/templates/_names.tpl
Use arg-driven default value for the secret key name instead of hard-coding the default value. This is needed for cases where the default value will not be consistent across charts. 
* Refactor helper function
> refactor: Use a default key name for generating secret key name

- charts/knative-serving-core/Chart.yaml
- charts/knative-serving-core/README.md
- charts/knative-serving-core/templates/deployments/activator.yaml
- charts/knative-serving-core/templates/deployments/controller.yaml
- charts/knative-serving-core/templates/deployments/webhook.yaml
- charts/knative-serving-core/templates/pdbs/activator.yaml
- charts/knative-serving-core/templates/pdbs/webhook.yaml
The current PDB configuration is too strict and prevents small deployments from being voluntarily disrupted during upgrades.
Change default PDBs from `minAvailable: 80%` to `maxUnavailable: 1`.
Also, make deployment replicas configuration only applied when autoscaling is turned off.
> chore(knative): fix PDB configuration for knative pods

- charts/knative-serving-core/Chart.yaml
- charts/knative-serving-core/README.md
- charts/knative-serving-core/crds/autoscaling-metrics.yaml
- charts/knative-serving-core/crds/cluster-domain-claims.yaml
- charts/knative-serving-core/crds/configurations.yaml
- charts/knative-serving-core/crds/domain-mappings.yaml
- charts/knative-serving-core/crds/image-caching.yaml
- charts/knative-serving-core/crds/ingresses.yaml
- charts/knative-serving-core/crds/networking-certificates.yaml
- charts/knative-serving-core/crds/pod-autoscalers.yaml
- charts/knative-serving-core/crds/revisions.yaml
- charts/knative-serving-core/crds/routes.yaml
- charts/knative-serving-core/crds/serverless-services.yaml
- charts/knative-serving-core/crds/services.yaml
- charts/knative-serving-core/templates/_helpers.tpl
- charts/knative-serving-core/templates/config-maps/autoscaler.yaml
- charts/knative-serving-core/templates/config-maps/defaults.yaml
- charts/knative-serving-core/templates/config-maps/features.yaml
- charts/knative-serving-core/templates/config-maps/gc.yaml
- charts/knative-serving-core/templates/config-maps/network.yaml
- charts/knative-serving-core/templates/mutating-webhooks/domain-mapping.yaml
- charts/knative-serving-core/templates/services/activator.yaml
- charts/knative-serving-core/templates/validating-webhooks/domain-mapping.yaml
- charts/knative-serving-core/values.yaml
Current knative version that we are currently using (1.3.3) suffers from issue in readiness probe after restart (https://github.com/knative/serving/issues/12571). The fix to the issue is in 1.7.X. 
Note: current knative serving version is 1.8.0, however there are breaking change that will take longer to analyse so we settle with 1.7.X 
Update chart based on knative release 1.7.4
> feat: Update knative-serving-core to 1.7.4

- charts/knative-serving-istio/Chart.lock
- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
- charts/knative-serving-istio/templates/deployments/net-istio-controller.yaml
- charts/knative-serving-istio/values.yaml
Current knative version that we are currently using (1.3.3) suffers from issue in readiness probe after restart (https://github.com/knative/serving/issues/12571). The fix to the issue is in 1.7.X. 
Note: current knative serving version is 1.8.0, however there are breaking change that will take longer to analyse so we settle with 1.7.X 
Update knative-serving-istio chart based on knative istio release 1.7.1
Notes: requires https://github.com/caraml-dev/helm-charts/pull/162 to be merged first to pass the test
> feat: Update knative-serving-istio chart to 1.7.1

- charts/observation-service/Chart.yaml
- charts/observation-service/README.md
- charts/observation-service/templates/deployment.yaml
- charts/observation-service/templates/fluentd-statefulset.yaml
- charts/observation-service/values.yaml
The current Observation Service helm chart does not support adding `annotations` to pods, which are required for Prometheus metrics scrapping.
Add annotations to Observation Service Deployment and Observation Service Fluentd StatefulSet manifests.
> feat: Add annotations for Observation Service pods

- charts/timber-fluentd/Chart.yaml
- charts/timber-fluentd/README.md
- charts/timber-fluentd/templates/configmap.yaml
- charts/timber-fluentd/templates/secret.yaml
- charts/timber-fluentd/templates/statefulset.yaml
- charts/timber-fluentd/tests/fluentd_test.yaml
Remove unnecessary suffix for fluentd chart. When installing as a subchart the statefulset can be suffix `fluentd` by the fullname twice which is unnecessary. 
Removing suffix for metadata names
> fix: timber fluentd - remove component suffix

- charts/observation-service/Chart.yaml
- charts/observation-service/README.md
- charts/observation-service/templates/_helpers.tpl
In order to scrape metrics using ServiceMonitor, it expects `app` and `release` labels to be added to Observation Service's Service CR. This PR ensures the missing `release` label is added.
Update helper template for Observation Service helm chart.
> fix: Add missing release label for Observation Service helm chart

- charts/timber-observation-service/.helmignore
- charts/timber-observation-service/Chart.yaml
- charts/timber-observation-service/README.md
- charts/timber-observation-service/README.md.gotmpl
- charts/timber-observation-service/templates/_helpers.tpl
- charts/timber-observation-service/templates/deployment.yaml
- charts/timber-observation-service/templates/hpa.yaml
- charts/timber-observation-service/templates/secrets.yaml
- charts/timber-observation-service/templates/service-monitor.yaml
- charts/timber-observation-service/templates/service.yaml
- charts/timber-observation-service/tests/observation_service_deployment_test.yaml
- charts/timber-observation-service/values.yaml
As a follow up PR to https://github.com/caraml-dev/helm-charts/pull/164, this PR adds the new timber-observation-service which will use new timber-fluentd. 
Changes up to https://github.com/caraml-dev/helm-charts/pull/169 is ported over. 
On top of breaking up the observation-service, several minor enhancements are added.
Deletion of the old observation-service will be carried out later, once the consumers has migrated to this new chart.
Current version of obs-service is `0.1.4` and appVersion is `0.1.0`, releasing this chart as `0.2.0` while maintaining the same appVersion as the underlying obs-service image is not changed.
- Porting of existing observation-service 
- Added example to various configuration in `values.yaml` on fluentd configuration
- Removal of …
> feat: add timber obs service using timber fluentd subchart

- charts/observation-service/Chart.yaml
- charts/observation-service/README.md
- charts/observation-service/templates/fluentd-hpa.yaml
- charts/observation-service/templates/hpa.yaml
- charts/observation-service/tests/fluentd_hpa_test.yaml
- charts/observation-service/tests/observation_service_deployment_hpa_test.yaml
- charts/timber-fluentd/Chart.yaml
- charts/timber-fluentd/README.md
- charts/timber-fluentd/templates/hpa.yaml
- charts/timber-fluentd/tests/fluentd_hpa_test.yaml
- charts/timber-observation-service/Chart.yaml
- charts/timber-observation-service/README.md
- charts/timber-observation-service/templates/hpa.yaml
- charts/timber-observation-service/tests/observation_service_deployment_hpa_test.yaml
- charts/timber-observation-service/tests/observation_service_deployment_test.yaml
Timber helm charts currently use `HorizontalPodAutoscaler` for `apiVersion: autoscaling/v1`. The current specification is supported for `apiVersion: autoscaling/v2` and hence is defined incorrectly.
Update `HorizontalPodAutoscaler` CR and add tests.
> fix(timber): Amend helm charts HPA CR

- charts/routes/Chart.yaml
- charts/routes/README.md
- charts/routes/templates/certs.yaml
- charts/routes/values.yaml
By default routes chart will create CertificateIssuer, which issues self-signed certificates. The goal is to make this behaviour customizable and allow users to use custom issuers.
- make creation of ClusterIssuer optional
> feat(routes): allow users to use provided CertificateIssuer

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/templates/mlflow-deployment.yaml
- charts/merlin/templates/mlflow-service.yaml
After adding `app` label to the template `merlin.label` chart started generating resources with duplicated labels in mlflow service and deployments.
Remove `app` label from `mlflow` templates
> fix(merlin): remove redundant labels for mlflow service and deployment

- charts/observation-service/Chart.yaml
- charts/observation-service/README.md
- charts/observation-service/templates/fluentd-hpa.yaml
- charts/timber-fluentd/Chart.yaml
- charts/timber-fluentd/README.md
- charts/timber-fluentd/templates/hpa.yaml
The incorrect `scaleTargetRef` was used for all Fluentd CR in Timber-related helm charts.
Use `StatefulSet` instead of `Deployment` for all Fluentd CR in Timber-related helm charts.
> fix: Timber fluentd HPA CR scaleTargetRef

- charts/routes/Chart.yaml
- charts/routes/README.md
- charts/routes/templates/_helpers.tpl
- charts/routes/templates/mlp-vs.yaml
- charts/routes/values.yaml
Sometimes we need to configure extra mappings in VS routing part to support cases like legacy authentication, etc.
- add extra section to mlp-vs
- adjust JWT check
> feat(routes): add possibility of configuring extra mappings for virtualservice

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/configmap.yaml
- charts/mlp/tests/mlp_cm_test.yaml
ApiHost part in the configMap always evaluates to `/api/v1` in caraml but it must be `/api`. 
* Update the globApiHost variable to get the compatible value
> fix: Update the globApiHost variable to get the compatible value

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
- scripts/generate-cluster-creds.sh
This PR bumps caraml to version 0.4.30, to use Merlin's new version 0.10.1
* `./scripts/generate-cluster-creds.sh` now modifies caraml chart's ci/ci-values.yaml file as well
> chore: Update caraml version to 0.4.30

- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
- charts/knative-serving-istio/templates/deployments/net-istio-controller.yaml
A duplicate label was causing JSON marshalling failure
- removed duplicate
> fix(knative): remove duplicate label

- charts/observation-svc/Chart.lock
- charts/observation-svc/Chart.yaml
- charts/observation-svc/README.md
Follow up to https://github.com/caraml-dev/helm-charts/pull/175, as the chart name was reduce due to char limits in kubernate resource
Depdencies rename from `timber-fluentd` to `fluentd`
> chore: update observation service fluentd dep name

- charts/knative-serving-istio/Chart.yaml
- charts/knative-serving-istio/README.md
- charts/knative-serving-istio/templates/peer-authentication/domain-mapping-webhook.yaml
- charts/knative-serving-istio/templates/peer-authentication/net-istio-webhook.yaml
Some resources in knative istio chart have configuration where integer is used as a key in yaml map:
```yaml
portLevelMtls:
8443:
mode: PERMISSIVE
```
This is a known but not yet fixed error https://github.com/kubernetes-sigs/kustomize/issues/3446
Quote integers
> fix(knative): use quotes for port mappings to prevent kustomize errors

- charts/fluentd/Chart.yaml
- charts/fluentd/README.md
- charts/fluentd/templates/_helpers.tpl
- charts/fluentd/templates/configmap.yaml
- charts/fluentd/templates/hpa.yaml
- charts/fluentd/templates/secret.yaml
- charts/fluentd/templates/service.yaml
- charts/fluentd/templates/statefulset.yaml
Template variables in `fluentd` helm chart still use `timber-fluentd` as name. It's inconsistent with the chart name and might confuse users of the chart.
Rename `timber-fluentd` template variables to `fluentd`
> chore: [fluentd] Rename template variable

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
This PR bumps caraml chart to use the merlin 0.10.2 and mlp 0.4.13
> chore: bump caraml version

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/postgres-secret.yaml
When the postgres helper functions are removed from the charts and moved to common chart. Their usage is not moved for this scenario. When enabled and external postgres secret is created. It needs to use the common helper functions.
> fix(mlp): Common helper functions to be used in postgres-secret

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
Default `cpu` value was incorrectly used when resource specification for imagebuilder was introduced in https://github.com/caraml-dev/helm-charts/pull/212.
Ensure default `cpu` value is of string type.
> fix: Update Merlin helm chart with valid default resource values

- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/service.yaml
- charts/xp-management/values-global.yaml
Add support for overriding XP Management's Service CRD's name.
Add global service name override.
> feat: Support XP Management Service CRD name override

- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/templates/deployment.yaml
- charts/xp-treatment/values.yaml
`replicaCount` is being shifted under `deployment`, similar to how all other charts define it.
Update reference to `replicaCount`.
> feat(xp-treatment): Shift replicaCount parameter under deployment

- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
To standardize with other charts in the repository, we should remove the `v` prefix from `xp-management` chart's `appVersion`.
Removed the `v` prefix from `xp-management` chart's `appVersion`.
> feat(xp-management): Remove v prefix from chart appVersion

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/deployment.yaml
- charts/mlp/values.yaml
Allow extra labels in deployment.
* Add support for mlp deployment to have extra labels added via values.yaml
> feat: Add support for mlp deployment to have extra labels added in values

- .github/workflows/test.yaml
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/tests/merlin_deployment_test.yaml
- charts/merlin/values.yaml
Recent change on standard transformer, introducing enable gRPC client keep alive and also publish prediction log. This PR adding the required helm chart changes to enable configuration change
Adding several environment variables
```
transformer.feast.grpc.keepAliveEnabled
transformer.feast.grpc.keepAliveTime
transformer.feast.grpc.keepAliveTimeout
transformer.model.grpc.keepAliveEnabled
transformer.model.grpc.keepAliveTime
transformer.model.grpc.keepAliveTimeout
transformer.kafka.brokers
transformer.kafka.maxMessageSize
pyfuncGRPCOptions
```
> feat: Adding standard transformer keep alive & kafka configurations

- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/values.yaml
`v0.12.0` version of XP has been released, and helm chart docker image version should be bumped.
Bump XP Management helm chart and docker image versions.
> chore(xp): Bump xp-management helm chart version

- charts/xp-treatment/Chart.lock
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/values.yaml
`v0.12.0` version of XP has been released, and helm chart docker image version should be bumped.
Bump XP Treatment helm chart and docker image versions.
> chore(xp): Bump xp-treatment helm chart version

- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/values.yaml
- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/values.yaml
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/values.yaml
Turing and XP have had recent releases. Updating their app versions accordingly, and bumping the chart version.
For `turing`, `xp-management` and `xp-treatment`, updating the values files and Chart.yaml.
> chore: update Turing and XP app versions

- charts/caraml-authz/Chart.yaml
- charts/caraml-authz/README.md
- charts/caraml-authz/templates/bootstrap-policy-job.yaml
- charts/caraml-authz/templates/bootstrap-role-job.yaml
This MR modifies the job resources that are used to create keto roles and policies by removing the `post-install` annotation. Previously, the `post-install` annotations specified on the jobs resulted in the job resources being created after all other resources were created successfully when `--wait` flag is passed when running `helm install` command
This causes all installations that use `--wait` flag to fail if the resources in the helm chart require the K8s jobs to run first.
> fix(caraml-authz): Modify policy and role creation k8s job

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/values.yaml
As part of MLP applications V2 API implementation (https://github.com/caraml-dev/mlp/pull/72) and recent upgrade to latest MLP UI version (https://github.com/caraml-dev/merlin/pull/378) in Merlin, we should remove `/v1` from the MLP API host used by the Merlin UI.
Remove `apiPrefix` from host variable used for setting `REACT_APP_MLP_API` environment variable.
> chore(merlin): Remove v1 prefix for UI API config

- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/turing-deployment.yaml
- charts/turing/templates/turing-service-account.yaml
- charts/turing/values.yaml
Previously, the `useInClusterConfig` was partially driving the creation of the service account. However, this is confusing. Also, existing service accounts could not be associated to the Turing deployment if `useInClusterConfig` was set to `false`.
This PR updates the service account association such that the deployment will always use a service account - by default, an SA with the name `turing` will be created. An existing SA can be used if `serviceAccount.create` is set to `false`.
> fix: Fix service account creation in Turing chart

- .github/workflows/chart-bumper.yaml
- scripts/chart_bumper.py
So far, The chart-bumper workflow upgrades the charts by only patch versions. eg: 1.3.4 -> 1.3.7 is upgraded via this but 1.3.4 -> 1.4.0 isn't. This PR will allow minor version upgrades while looking for new chart releases.
Set flag to true
> ci: Allow minor chart version upgrades in chart-bumper

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
- charts/caraml/values.yaml
Similar to https://github.com/caraml-dev/helm-charts/pull/258, https://github.com/caraml-dev/helm-charts/pull/257, and https://github.com/caraml-dev/helm-charts/pull/255 which removes the need for encryption key in mlp
Remove encryption key config from top level CaraML chart
> feat: remove encryption key from caraml chart

- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/turing-service.yaml
Make svc name consistent with other caraml components.
* Add global value override for svc name
> fix(turing): use global svc name when needed

- charts/caraml/Chart.yaml
- charts/caraml/README.md
- charts/caraml/values.yaml
- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/ci/ci-values.yaml
- charts/turing/values-global.yaml
Avoid double slash when creating mlp url in caraml and turing chart
Set default mlp apiPrefix to empty string instead of slash ("/")
> fix: update mlp api prefix

- charts/caraml-store/Chart.yaml
- charts/caraml-store/README.md
- charts/caraml-store/templates/registry/deployment.yaml
- charts/caraml-store/templates/serving/deployment.yaml
envOverride is currently broken when the value of the override is of the map type. 
Fix the indentation for envOverride
> fix(caraml-store): use correct indentation for map type envoverride

- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/_helpers.tpl
- charts/xp-management/templates/deployment.yaml
Missing node selectors in deployment manifests for xp-management. 
* Add node selector
* Use global oauthClientId if present.
> fix(xp): Add node selector for xp-mgmt deployment

- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/turing-deployment.yaml
- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/deployment.yaml
templates to add Tolerations are missing in deployment manifests.
* add tolerations to turning, xp-mgmt deployments
> fix: Add missing tolerations in turing, xp-mgmt chart

- charts/xp-treatment/Chart.lock
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/templates/deployment.yaml
templates to add Tolerations are missing in deployment manifests.
add tolerations to xp-treatment deployments
> fix: Add missing tolerations in xp-treatment chart

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/_helpers.tpl
- charts/mlp/templates/configmap.yaml
- charts/mlp/tests/mlp_cm_test.yaml
- charts/mlp/values.yaml
Per the current implementation, the MLP configmap's structure is largely fixed. This means that, with every new config introduced, the chart must be updated, which is not ideal.
This PR refactors the MLP configs (moving them from `.Values.deployment` -> `.Values.config`) and configmap (merging the `.Values.config` with a set of default configs generated from other values in the chart), so that the configs can be dynamically extended. This is similar to other components like Turing.
* `charts/mlp/templates/_helpers.tpl` - Create default MLP config that can be merged with `.Values.config`
* `charts/mlp/templates/configmap.yaml` - Let configmap use the merged config
* `charts/mlp/tests/mlp_cm_test.yaml` - Update tests:
- Key order matters in regex matches of configmap, now they are sorted …
> chore(mlp): Refactor app configs

- .github/workflows/chart-bumper.yaml
Remove the flag to bump minor version. This will be handled later since it has external deps upgraded and it needs fixes before merging. To unblock the auto-upgrades this flag is removed.
> chore: revert minor version bump in chart bumper

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
This PR simply updates the caraml component dependencies in the umbrella chart, to consume the latest changes.
> chore: Bump up dependencies on CaraML umbrella chart

- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/_helpers.tpl
- charts/xp-management/tests/secret_test.yaml
- charts/xp-management/values.yaml
Since MLP url value is used in determining the value for the default config, the overwrite in the config generation is causing issues. It results in the generated value never being used.  This MR fixes the same. 
* update config generation logic. 
* Add tests.
> fix(xp): update the logic for default config creation

- charts/common/Chart.yaml
- charts/common/README.md
In #254, a tiny change was made to one of the comments in the templates of the `common` chart, though the overall chart version was not updated. This caused an error to occur in the CD job to release a new chart version: https://github.com/caraml-dev/helm-charts/actions/runs/5342383824/jobs/9684150972#step:6:58. 
This PR simply bumps up the common chart version to fix the issue above.
> chore(caraml): bump up common chart version

- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/templates/hpa.yaml
Autoscaling API version `autoscaling/v2beta2` is removed in Kubernetes 1.26: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126
Upgrading the xp-treatment chart to use `autoscaling/v2` that's available since Kubernetes 1.23
> chore(xp-treatment): Upgrade hpa API to autoscaling/v2

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
In #254, a new schema was introduced due to the refactored Helm chart. #306 then tried to address some of the formatting issues with the chart as it was subsequently discovered that the refactoring was not without issues. However, it is found again that certain default Helm chart values which were originally present have been unintentionally removed; this PR thus adds these values back again (in its new yaml based schema) so that consumers of the Merlin chart do not need to explicitly specify them. 
This PR also removes fields unused by the Merlin API server:
- `BuildContextURI` - see this PR https://github.com/caraml-dev/merlin/pull/416/files
- `PredictionJobBuildContextURI` - see this PR https://github.com/caraml-dev/merlin/pull/416/files
- `EncryptionKey` - see …
> fix(merlin): Add additional default values

- charts/caraml-authz/Chart.yaml
- charts/caraml-authz/README.md
- charts/caraml-authz/templates/_helpers.tpl
- charts/caraml-authz/tests/deployment_test.yaml
> set MaxIdleConns and MaxOpenConns to 0, which means there will be [no limit to the number of open connections to the database](https://pkg.go.dev/database/sql#DB.SetMaxOpenConns)
To restrict the number of open and idle connections to the database.
> chore: add max conns, max-idle-conns for db connection for caraml-authz

- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/deployment.yaml
Currently, it is not possible to deploy the XP Management Service with an existing SA.
This PR updates the XP Management Service deployment specs to always associate an SA - it will be created if `serviceAccount.create` is set to true. If not, the chart will expect an existing SA. This is similar to Turing and other charts.
> fix: XP Management Service can be deployed with existing SA

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
Since standard transformer use opentelemetry for tracing, previous env variable for jaeger tracing is not usable. Hence this PR remove unused keys and add new collector endpoint url
* Remove unused jaeger env variable
* Adding colector endpoint url
> feat(merlin): Remove unused key and add new one for jaeger collector URL

- charts/turing/Chart.lock
- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/ci/ci-values.yaml
- charts/turing/templates/_helpers.tpl
- charts/turing/values.yaml
- scripts/generate-cluster-creds.sh
The GitHub PR addresses two separate issues, with two separate changes:
- The Merlin chart dependency in Turing is (very) outdated (`0.10.21`)-> Bump up Merlin version (`0.11.4`) 
- Fixing the `cannot overwrite table with non table for merlin.imageBuilder.k8sConfig (map[])` warning when running `helm template .` or `helm lint .` in `helm-charts/charts/turing` -> Convert the `imageBuilder.k8sConfig` struct into a YAML map just like for Merlin 
The first issue's self evident so nothing much to talk there. As for the second, it turns out after some debugging that the recursive `coalesceTablesFullKey` [function](https://github.com/helm/helm/blob/v3.12.2/pkg/chartutil/coalesce.go#L220) (from Helm) called onto the YAML configs in the parent Turing values file actually causes …
> chore(turing): remove conversion of k8sConfig to json

- .github/workflows/test.yaml
- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
- scripts/generate-cluster-creds.sh
This MR updates the version of Turing used in the overarching CaraML chart. In addition, it also cleans up the cluster credential generation script that's intended for both the Merlin and Turing apps, since both of them are now expecting these credentials to be passed in YAML.
- `charts/caraml/Chart.yaml` - Bump up of Turing version
- `scripts/generate-cluster-creds.sh` - Clean up of cluster credential generation script
> chore(caraml): Update Turing chart version manually

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/merlin-deployment.yaml
Passing `extraEnvs`:
```yaml
deployment:
extraEnvs: 
- name: NAME
value: VALUE
```
Causing rendering error:
```
Error: YAML parse error on caraml/charts/merlin/templates/merlin-deployment.yaml: error converting YAML to JSON: yaml: line 77: did not find expected key
```
Fixing by changing `nindent` parameter from 8 to 10
> fix(merlin): passing extraEnvs causing helm rendering error

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/tests/merlin_config_secret_test.yaml
- charts/merlin/values.yaml
Fix getting Kaniko service account name
Use include instead of template in _helpers.tpl
> fix(merlin): Use include to get merlin.kaniko-sa value

- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/_helpers.tpl
- charts/turing/templates/kaniko-service-account.yaml
- charts/turing/templates/turing-deployment.yaml
- charts/turing/values.yaml
Similar to how https://github.com/caraml-dev/merlin/pull/352 introduced a Kubernetes service account to be used for Kaniko jobs orchestrated by Merlin, this PR similarly introduces a similar change for Turing in its chart. 
Note that this PR has to be merged first (for the chart to be published before being used in this PR https://github.com/caraml-dev/turing/pull/357 in the Turing repo that includes the API server changes).
- `charts/turing/templates/_helpers.tpl` - Addition of the Turing Kaniko service account in the default Turing configs
- `charts/turing/templates/kaniko-service-account.yaml` - Addition of the new Turing Kaniko Kubernetes service account manifest
- `charts/turing/values.yaml` - Addition of default Turing image builder service account values
> chore(turing): Add Kaniko service account to Turing chart

- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/_helpers.tpl
- charts/xp-management/templates/deployment.yaml
Similar to one of the changes in PR #334, a tiny fix is introduced to the XP Management chart such that the service account name is only injected into the XP Management Service deployment only when we are expecting one to be created or if its name is specified explicitly.
- `charts/xp-management/templates/deployment.yaml` - Addition of logical check before the service account name is added
- `charts/xp-management/templates/_helpers.tpl` - Simplification of the definition for `serviceAccountName` (there is no way the `"default"` name will ever be used, since `serviceAccountName` is never used unless `.Values.deployment.serviceAccount.create` or `.Values.deployment.serviceAccount.name` is true; see the fix above)
> fix(xp-management): Make XP Management chart use service account selectively

- charts/xp-treatment/Chart.lock
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/templates/_helpers.tpl
- charts/xp-treatment/templates/deployment.yaml
- charts/xp-treatment/templates/service-account.yaml
- charts/xp-treatment/values.yaml
This PR introduces a Kubernetes service account for the XP Treatment Service that will allow it to use Google service account credentials via workload identity instead of them being mounted as a volume.
- `charts/xp-treatment/templates/_helpers.tpl` - Addition of the XP Treatment Service service account block in the default XP Treatment Service configs
- `charts/xp-treatment/templates/service-account.yaml` - Addition of the new XP Treatment Service Kubernetes service account manifest
- `charts/xp-treatment/values.yaml` - Addition of default XP Treatment Service service account values
> chore(xp-treatment): Add k8s service account to XP Treatment chart

- charts/routes/Chart.yaml
- charts/routes/README.md
- charts/routes/values.yaml
- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/service-swagger.yaml
This PR fixes 2 separate issues that affect the swagger docs of the Turing and XP Management charts:
1. The Turing swagger docs endpoint is not supposed to be accessed without a trailing slash (see [this](https://github.com/caraml-dev/turing/blob/78ca7b32f36e4cb3095346262c63f928c54f82d3/api/turing/config/config.go#L638) for the default value set). This PR adds a slash to the default value of the Turing swagger UI endpoint.
2. The XP Management swagger UI service was unfortunately using the full name of the release as its resource name, unlike most other CaraML components which were simply using the component name. This PR introduces a new template variable to be used for the swagger UI service name (of the form `[component-name]-swagger`) instead. (see …
> fix(turing,xp-management): Fix swagger k8s service routes

- charts/xp-treatment/Chart.lock
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/ci/ci-values.yaml
- charts/xp-treatment/templates/service-swagger.yaml
- charts/xp-treatment/templates/service.yaml
Similar to the second bug fix in PR #339, this PR replaces the swagger UI service name with the same name for the XP Treatment K8s service resource with the suffix `-swagger` appended to it.
- Fixed XP Treatment swagger docs service UI name
> fix(xp-treatment): Fix xp treatment swagger ui service

- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/values.yaml
After chart version 0.6.1, the minimum compatible MLP version is 1.10.1.
- Update default image for MLP.
> feat: Update default MLP image tag to be Keto 0.11 compatible

- charts/merlin/Chart.lock
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
The current Merlin chart does not work out of the box for MLP app version 1.10.0 / chart version 0.6.1  onwards. After this PR, by default, the MLP version bundled together with Merlin will be Keto 0.11 compatible. The default configuration for Merlin has also been updated.
- Default Merlin configuration
- Chart dependencies
- Update default image tag
> feat: Update Merlin chart to use keto 0.11 compatible mlp chart

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
- charts/caraml/ci/ci-values.yaml
- charts/caraml/values.yaml
Merlin and MLP charts have been updated to be compatible with Keto 0.11. The umbrella chart is updated to use the newer version of the charts.
There are some follow up to be done after this PR is merged:
- Clean up caraml-authz completely
- Clean up the helper functions that are associated with caraml-authz
- Clean up the global variables
- (Good to have) install ext authz extension on Istio by default, install istio authorization policy using route chart
- Disable authorization on Turing by default (not done for XP, as authorization is already turned off by default in XP chart)
- Install MLP together with Keto by default
- Disable caraml-authz chart
> feat: Update caraml umbrella chart to be Keto 0.11 compatible

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/values.yaml
This PR replaces the default merlin standard transformer image in its chart values file because it does not follow the usual convention of a container image name, which creates potential errors if any deployment depends on that default value working correctly.
This PR also fixes 3 other bugs:
- inserting a Kaniko service account name into the Merlin configs if we are not expecting one to be created or if the name is not specified anywhere
- inserting a service account name into the Merlin deployment if we are not expecting one to be created or if the name is not specified anywhere
- ~~misleading `app.kubernetes.io/version=[app version]` label for Merlin resources when the app version is rarely updated (and not necessarily expected to be updated all the time)~~ (removed and to be decided …
> fix(merlin): Fix default merlin standard transformer image

- charts/routes/Chart.yaml
- charts/routes/README.md
- charts/routes/templates/_helpers.tpl
- charts/routes/tests/oathkeeper_rules_test.yaml
The oathkeeper rules template currently don't consider the global domain when constructing the regex to match the MLP host name. After this fix, the regex constructed will now be consistent with the MLP virtual service host name.
- Update oathkeeper rule
> fix: fix incorrect mlp console regex in oathkeeper rule

- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/deployment.yaml
`extraEnvs` aren't rendered correctly that cause helm to fail 
fix indentation
> fix(xp): extraEnvs rendering has wron indentation

- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/_helpers.tpl
- charts/turing/templates/turing-deployment.yaml
- charts/turing/templates/turing-service.yaml
- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/_helpers.tpl
- charts/xp-management/templates/deployment.yaml
- charts/xp-management/templates/service-swagger.yaml
This PR introduces fixes to the Turing and XP Management charts:
The XP Management swagger docs are not functioning correctly if the full name of the XP management app does not happen to be the same as its regular name. That's because the swagger K8s service is using the full name as a label selector whereas the XP Management deployment pods are simply using a regular name as a label. 
Compare:
- https://github.com/caraml-dev/helm-charts/blob/main/charts/xp-management/templates/service-swagger.yaml#L18
- https://github.com/caraml-dev/helm-charts/blob/main/charts/xp-management/templates/deployment.yaml#L23
This PR thus updates the selector value to use the regular name of the XP Management service.
The Turing deployment pod labels and service pod selectors are using the full name of the …
> fix(turing,xp-management): Fix Turing and XP app labels

- charts/xp-treatment/Chart.lock
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/templates/service-swagger.yaml
Similar to PR #353, the XP Treatment swagger docs are not functioning correctly if the full name of the XP Treatment app does not happen to be the same as its regular name. That's because the swagger K8s service is using the full name as a label selector whereas the XP Treatment deployment pods are simply using a regular name as a label.
Compare:
- https://github.com/caraml-dev/helm-charts/blob/main/charts/xp-treatment/templates/deployment.yaml#L22
- https://github.com/caraml-dev/helm-charts/blob/main/charts/xp-treatment/templates/service-swagger.yaml#L18
This PR thus updates the selector value to use the regular name of the XP Treatment service.
- `charts/xp-treatment/templates/service-swagger.yaml` - Update of the XP swagger service pod selector
> fix(xp-treatment): Fix incorrect selector in xp treatment

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/README.md.gotmpl
- charts/merlin/templates/_config.tpl
- charts/merlin/templates/_helpers.tpl
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/tests/merlin_config_secret_test.yaml
- charts/merlin/tests/merlin_deployment_test.yaml
- charts/merlin/values.yaml
- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/README.md.gotmpl
- charts/turing/templates/_config.tpl
- charts/turing/templates/_helpers.tpl
- charts/turing/tests/turing_config_secret_test.yaml
- charts/turing/tests/turing_deployment_test.yaml
- charts/turing/values.yaml
* This MR modifies merlin helm chart to render all configs and deployment tag using the field `.Values.releasedVersion`
* The purpose is to update all configs that share this tag using 1 value in values.yaml
* A new field is added in both Merlin and Turing's `values.yaml` called `rendered`
```yaml
rendered:
releasedVersion: v1.0.0
...
otherFields:
```
* The fields in `rendered` will be used to generate partial templates. The idea is to configure fields that are reused multiple times across different templates in the chart. For example, the image tag field in Merlin is reused in [deployment.yaml](./merlin/templates/merlin-deployment.yaml) and [merlin-config-secret.yaml](./merlin/templates/merlin-deployment.yaml)
* This reduces the number of places to update whenever there is a new release …
> feat: Add new top level field rendered for template variables

- .pre-commit-config.yaml
- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/ci/ci-values.yaml
- charts/xp-management/templates/_helpers.tpl
- charts/xp-management/values.yaml
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/ci/ci-values.yaml
- charts/xp-treatment/templates/_helpers.tpl
- scripts/helm-docs.sh
The existing xp helper templates do not handle extraLabels correctly.
Before:
```
108   │   labels:
109   │     app: xp-management
110   │     release: xp-management
111   │     app.kubernetes.io/name: xp-management
112   │     helm.sh/chart: "xp-management-0.2.8"
113   │     app.kubernetes.io/version: "0.12.1"
114   │     app.kubernetes.io/instance: xp-management
115   │     app.kubernetes.io/managed-by: Helm
116   │     app.kubernetes.io/part-of: caramlsdfoo: 123 <--
```
white space on the right gets chomped, which causes the rendering to fail.
After:
```
24   │   labels:
25   │     app: xp-management
26   │     release: xp-management
27   │     app.kubernetes.io/name: xp-management
28   │     helm.sh/chart: "xp-management-0.2.8"
29   │     app.kubernetes.io/version: "0.12.1"
30   │ …
```
> fix(xp): template whitespace issue

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_config.tpl
- charts/merlin/templates/_helpers.tpl
- charts/merlin/tests/merlin_config_secret_test.yaml
- charts/merlin/values.yaml
- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/_helpers.tpl
- charts/turing/tests/turing_config_secret_test.yaml
- charts/turing/values.yaml
* Current implementation of rendering templates of merlin and turing using `render` field is incomplete. This MR introduces a new field `overwrites`, to overwrite specific fields that the render produces. 
* New `render.overwrites` field to overwrite portions of the rendered template
* If render is empty, falls back to original mechanism of using `.Values.config` and `$defaultConfig`
For example, the current implementation does not allow the following config to be rendered in merlin:
```
BaseImages:
3.7.*:
ImageName: ghcr.io/caraml-dev/merlin/merlin-pyfunc-base-py37:0.34.0-rc1
DockerfilePath: "python/pyfunc-server/docker/Dockerfile"
BuildContextURI: "git://github.com/caraml-dev/merlin.git#refs/tags/v0.34.0-rc1"
...
3.10.*:
ImageName: …
```
> fix: Allow overwriting of rendered template in merlin and turing charts

- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/_config.tpl
This MR removes unnecessary values in turing's rendered template. It adds an optional field in `rendered` to specify the EnsemblerService tag, which defaults to the ensemberTag if left unspecified.
> fix: remove extra values in helm rendered template

- .github/workflows/lint.yaml
It looks like the GCS object used by 1 of the internal steps in the `chart-testing-action` step is missing. This causes all testing steps to fail, eg
* https://github.com/caraml-dev/helm-charts/actions/runs/6717324797/job/18254985036
* https://github.com/caraml-dev/helm-charts/actions/runs/6717324794/job/18254985011
This MR bumps the `chart-testing-action` to use v2.6.0 from v2.4.0 which bumps the version of `cosign`
cc @tkpd-hafizhan @khorshuheng
> fix: Update chart-testing-action to 2.6.0

- .github/workflows/chart-bumper.yaml
- .github/workflows/test.yaml
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_config.tpl
- charts/merlin/tests/merlin_config_secret_test.yaml
- charts/merlin/values.yaml
- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/_config.tpl
- charts/turing/tests/turing_config_secret_test.yaml
- charts/turing/values.yaml
The latest release of Turing ([v1.16.0](https://github.com/caraml-dev/turing/releases/tag/v1.16.0)) and Merlin ([v0.35.0](https://github.com/caraml-dev/merlin/releases/tag/v0.35.0)) drop support for Python 3.7 altogether. This PR updates the chart specs accordingly.
* Update app versions for Turing and Merlin
* `charts/merlin/templates/_config.tpl`, `charts/turing/templates/_config.tpl` - Drop Python 3.7 from the helper template functions for the Pyfunc server images
* Update unit tests
> chore: Update Turing and Merlin charts with latest release specs

- charts/turing/Chart.lock
- charts/turing/Chart.yaml
- charts/turing/README.md
Turing's dependency on Merlin is outdated
* `charts/turing/Chart.yaml` - Updating Turing's dependency on Merlin
> chore: Update Turing's dependency on Merlin

- charts/caraml/Chart.lock
- charts/caraml/Chart.yaml
- charts/caraml/README.md
Update CaraML's dependency on Turing. This shouldn't be required to do manually, but I had to delete the CaraML chart release `0.8.12` to let this CI pass: https://github.com/caraml-dev/helm-charts/actions/runs/6728475864/job/18287888753#step:6:58
That likely messed up the automatic dep update.
> chore: Update CaraML's dependency on Turing

- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/templates/hpa.yaml
ArgoCD shows the HPA configs to be out of order. It expects `memory` to appear first and then `cpu`. This is a known issue:  https://github.com/argoproj/argo-cd/issues/1079
Reordering the HPA metrics.
> chore(xp-treatment): Update HPA configs for xp-treatment chart

- .github/workflows/test.yaml
- scripts/generate-cluster-creds.sh
During CI tests the generate cluster creds script is being invoked even for charts that have `caraml` in their name explicitly checking for the charts that need to be added. 
This MR will take care of scenarios where only one of the charts have changes or a combination of caraml, merlin, turing and other caram-* charts in the list of changed charts. 
* Script changes - condition checks for adding cluster creds.
> fix(ci): generate cluster credentials in CI test for explicitly caraml, merlin turing charts

- charts/caraml-authz/Chart.yaml
- charts/caraml-authz/README.md
- charts/caraml-authz/templates/_helpers.tpl
- charts/caraml-authz/templates/deployment.yaml
- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_helpers.tpl
- charts/merlin/templates/merlin-deployment.yaml
- charts/merlin/tests/merlin_deployment_test.yaml
- charts/mlp/Chart.yaml
- charts/mlp/README.md
- charts/mlp/templates/_helpers.tpl
- charts/mlp/templates/deployment.yaml
- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/_helpers.tpl
- charts/turing/templates/turing-deployment.yaml
- charts/turing/tests/turing_deployment_test.yaml
- charts/xp-management/Chart.yaml
- charts/xp-management/README.md
- charts/xp-management/templates/_helpers.tpl
- charts/xp-management/templates/deployment.yaml
- charts/xp-treatment/Chart.yaml
- charts/xp-treatment/README.md
- charts/xp-treatment/templates/_helpers.tpl
- charts/xp-treatment/templates/deployment.yaml
Version labels can be helpful during debugging. It is also shown on the Kiali dashboard.
Add `version` label to main CaraML components
> chore(caraml): harmonize version label

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_config.tpl
- charts/merlin/tests/merlin_config_secret_test.yaml
- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/_config.tpl
- charts/turing/tests/turing_config_secret_test.yaml
It's a common use case to use a private mirror for docker images. This PR updates Turing and Merlin charts so that the image names that are generated based on the released version will leverage the configured `deployment.image.registry` value.
* `charts/merlin/templates/_config.tpl` - Use `{{ .Values.deployment.image.registry }}` for the Pyfunc base images and standard transformer
* charts/turing/templates/_config.tpl - Use `{{ .Values.deployment.image.registry }}` for the Pyfunc base images and router
* Update unit tests to distinguish the override test case better
CC: @ariefrahmansyah @leonlnj
> chore(merlin|turing): Use configured image registry to generate default image names

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
In line with the changes introduced in https://github.com/caraml-dev/merlin/pull/539 to expose tolerations and node selectors on pods where Merlin batch jobs are run, we are introducing default values for these fields in the default Merlin Helm values file. These values were previously hardcoded in the Merlin API server files as variables.
- Add default tolerations and node selectors for Merlin batch jobs
> feat(merlin): Add default tolerations and node selectors for Merlin batch jobs 

- charts/turing/Chart.yaml
- charts/turing/README.md
The Turing app version has been updated v1.17.2 though the default version in the chart remained at v1.16.0. This PR simply updates the `appVersion` value so the latest version of Turing is used by default when installing it via its Helm chart.
- `charts/turing/Chart.yaml` - Bumping up of Turing from v1.16.0 to v1.17.2
> chore(turing): Update Turing app version to v1.17.2

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_config.tpl
In this [PR](https://github.com/caraml-dev/merlin/pull/550) we introduce ObservabilityPublisher config. This config have `imageName` field which is the value is depend on the released version that defined by the administrator
Set ObservabilityPublisher.ImageName value based on rendered  released version
> feat(merlin): Add observability publisher image in the config partial template

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/values.yaml
Merlin's default `values.yaml` has BatchConfig.NodeSelectors value configured which will no be overwritten if user modify the value on their own values file.
1. Remove BatchConfig.NodeSelectors default value
2. Update default value for imageBuilder.builderConfig.PredictionJobBaseImage.MainAppPath
> chore(merlin): Fix merlin batch job node selector default value

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/_config.tpl
Previous PR (https://github.com/caraml-dev/helm-charts/pull/408) removed PredictionJobBaseImage.MainAppPath from Merlin default values.yaml, however, if it's empty it will use the value from _config.tpl.
This PR updates the default PredictionJobBaseImage.MainAppPath in _config.tpl
> chore(merlin): Update PredictionJobBaseImage.MainAppPath in _config.tpl

- charts/caraml-store/Chart.yaml
- charts/caraml-store/README.md
- charts/caraml-store/templates/serving/deployment.yaml
Replica shouldnt be set if HPA is enabled.
> chore: avoid setting replica when HPA is defined

- .github/config/ct.yaml
- .github/workflows/test.yaml
- charts/feast-ui/Chart.yaml
- charts/feast-ui/README.md
- charts/feast-ui/values.yaml
The extra volume mount should have been a list instead of dictionary.
> feat: fix type for extra volume mount

- charts/routes/Chart.yaml
- charts/routes/README.md
- charts/routes/templates/xp-oathkeeper-rules.yaml
- scripts/install_metallib.sh
XP's `/validate` endpoint only [allows](https://github.com/caraml-dev/xp/blob/main/management-service/api/api.go#L2254) POST methods but these aren't allowed under the existing Oathkeeper rules (probably it got forgotten when the authentication mechanism of CaraML was changed). This PR adds POST methods to the existing methods (only GET exists currently) allowed for the non-project specific endpoints (i.e. `/treatment-service-config` and `/projects`). 
- Add POST method to existing XP Oathkeeper rule
> fix(xp): Add POST method to XP Oathkeeper rules

- .gitignore
- charts/caraml-store/Chart.yaml
- charts/caraml-store/README.md
- charts/caraml-store/templates/serving/deployment.yaml
- charts/caraml-store/values.yaml
The Caraml Store Serving service needs to maintain high availability due to the large volume of requests it handles. Therefore, it's crucial to ensure the application has completed its startup process using a startup probe. Additionally, if the service becomes unresponsive for an extended period, the pod should be restarted using a liveness probe.
Adding startup and liveness probe for caraml store serving deployments with default value
```yaml
startupProbe:
httpGet:
path: /actuator/health
port: 8080
periodSeconds: 5
timeoutSeconds: 1
failureThreshold: 10
livenessProbe:
httpGet:
path: /actuator/health
port: 8080
initialDelaySeconds: 0
periodSeconds: 10
timeoutSeconds: 2
failureThreshold: 5
```
> feat(serving): adding startup and readiness probe

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/tests/merlin_config_secret_test.yaml
- charts/merlin/tests/merlin_deployment_test.yaml
- charts/merlin/values.yaml
With the recent changes in the Merlin repo to update both the Merlin API server and Mlflow server, this PR updates the versions of these components in the Merlin Helm chart to ensure that the latest versions get deployed by default.
- Update of the `ghcr.io/gojek/mlflow:1.3.0` image for Mlflow to `ghcr.io/caraml-dev/mlflow:1.26.1` 
- Update of the Merlin API server image tag from `v0.38.0-rc1` to `v0.45.3`
- Addition of the `KanikoPushRegistryType` field to the default values file as it is now required in the newer version of the Merlin API server
> chore(merlin): Update merlin and mlflow versions

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/merlin-cluster-role-binding.yaml
- charts/merlin/templates/merlin-cluster-role.yaml
- charts/merlin/values.yaml
- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/templates/turing-cluster-role-binding.yaml
- charts/turing/templates/turing-cluster-role.yaml
- charts/turing/values.yaml
Allow enabling RBAC creation from values even when we don't use in-cluster config.
> feat: option for rbac creation

- charts/merlin/Chart.yaml
- charts/merlin/README.md
- charts/merlin/templates/mlflow-deployment.yaml
In PR #426, modifications were made to the Mlflow deployment template in order to allow it to be configured with additional environment variables specified under the `extraEnvs` field. 
However that was problematic as there was already an existing template block that already parses the values of `extraEnvs` as environment values in the deployment template.
See the following lines:
- https://github.com/caraml-dev/helm-charts/blob/main/charts/merlin/templates/mlflow-deployment.yaml#L76
- https://github.com/caraml-dev/helm-charts/blob/main/charts/merlin/templates/mlflow-deployment.yaml#L84
This PR cleans up the previous template block for the `extraEnvs` field in favour of the new one, which is simpler.
- `charts/merlin/templates/mlflow-deployment.yaml` - removal of a redundant block to …
> fix(mlflow): Remove redundant Mlflow extra envs mapping

- charts/turing/Chart.yaml
- charts/turing/README.md
- charts/turing/temp.yaml
- charts/turing/templates/_config.tpl
- charts/turing/tests/turing_config_secret_test.yaml
- charts/turing/values.yaml
Turing will have this [improvement](https://github.com/caraml-dev/turing/pull/404) where users can use any Python versions for their pyfunc ensembler, hence base image config for supported Python versions will not be needed anymore.
remove base image config for specific python versions
> feat: remove base image config for specific python versions
